service: sls-step-functions

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

#  environment:
#    variable1: value1

plugins:
  - serverless-offline

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
  world:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get

custom:
  serverless-offline:
    useDocker: true
