service: sls-step-functions

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-2'}

plugins:
  - serverless-offline
  - serverless-step-functions
  - serverless-step-functions-local
  - serverless-offline-lambda

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  assembleMedia:
    handler: bin/assembleMedia
    # events:
    #   - httpApi:
    #       path: /assembleMedia
    #       method: post
  distribution:
    handler: bin/distribution

stepFunctions:
  stateMachines:
    packageWorkflow:
      events:
        - http:
            path: /package
            method: post
      definition:
        Comment: "A package workflow"
        StartAt: AssembleMedia
        States:
          AssembleMedia:
            Type: Task
            Resource: 
              Fn::GetAtt: [assembleMedia, Arn]
            Next: CheckAssembleComplete
          CheckAssembleComplete:
            Type: Choice
            OutputPath: $.nextPayload
            Choices:
              - Variable: $.assembleComplete
                BooleanEquals: true
                Next: Distribution
            Default: AssembleMedia

          Distribution:
            Type: Task
            Resource:
              Fn::GetAtt: [distribution, Arn]
            End: true

custom:
  serverless-offline:
    useDocker: true
  stepFunctionsLocal:
    accountId: keyhole-dev
    region: us-west-2
